apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app
  name: nginx-app
  namespace: devops-challange
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-app
    spec:
      serviceAccountName: devops-sa
      containers:
      - image: nginx:1.22.0
        name: nginx
        env:
        - name: SECRET_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: API_KEY
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"


            
      

