apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo
 namespace: devops-challange
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-app
 minReplicas: 3
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50